tigerleaflet/urls.py
from django.conf.urls import url

from .views import CountryData
from .views import StateData
from .views import CountyData

app_name = 'tigerleaflet'
urlpatterns = [
    # geojson urls
    url(r'^country.geojson$',
        CountryData.as_view(),
        name='country_data'),
    url(r'^state.geojson$',
        StateData.as_view(),
        name='state_data'),
    url(r'^county.geojson$',
        CountyData.as_view(),
        name='county_data'),
]

tigerleaflet/models.py
from django.contrib.gis.db import models


class State(models.Model):
    fips_code = models.CharField('FIPS Code', max_length=2)
    usps_code = models.CharField('USPS state abbreviation', max_length=2, db_index=True)
    name = models.CharField(max_length=100, db_index=True)
    area_description_code = models.CharField(max_length=2)
    feature_class_code = models.CharField(max_length=5)
    functional_status = models.CharField(max_length=1)
    mpoly = models.MultiPolygonField()

    objects = models.GeoManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class County(models.Model):
    state = models.ForeignKey(State)
    # redundant field, but necessary until serializer overrides can be done
    usps_code = models.CharField('USPS state abbreviation', max_length=2)
    state_fips_code = models.CharField('State FIPS Code', max_length=2)
    fips_code = models.CharField('FIPS Code', max_length=3)
    county_identifier = models.CharField(max_length=5)
    name = models.CharField(max_length=100)
    name_and_description = models.CharField(max_length=100)
    legal_statistical_description = models.CharField(max_length=2)
    fips_55_class_code = models.CharField(max_length=2)
    feature_class_code = models.CharField(max_length=5)
    functional_status = models.CharField(max_length=1)
    mpoly = models.MultiPolygonField()

    objects = models.GeoManager()

    def save(self, *args, **kwargs):
        self.state = State.objects.get(fips_code=self.state_fips_code)
        self.usps_code = self.state.usps_code
        super(County, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Counties'

    def __str__(self):
        return self.name + ", " + self.usps_code

tigerleaflet/views.py
from django.core.serializers import serialize
from django.http import HttpResponse
from django.views.generic import View

from tigerleaflet.models import County
from tigerleaflet.models import State


def get_geojson(data, fields):
    return serialize('geojson', data, geometry_field='mpoly', fields=fields)


class CountryData(View):
    fields = ('name', 'usps_code', 'fips_code')

    def post(self, request):
        map_data = State.objects.raw(
            'SELECT id, ST_simplify(mpoly, 0.1) AS mpoly,'
            ' name, usps_code, fips_code'
            ' FROM tigerleaflet_state')
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')


class StateData(View):
    fields = ('name', 'usps_code', 'fips_code')

    def post(self, request):
        usps_code = self.request.POST['state'].upper()
        map_data = County.objects.raw(
            'SELECT id, ST_simplify(mpoly, 0.01) AS mpoly,'
            ' name, fips_code, usps_code FROM tigerleaflet_county'
            ' WHERE usps_code=%s', [usps_code],
        )
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')


class CountyData(View):
    fields = ('name', 'fips_code', 'usps_code')

    def post(self, request):
        usps_code = self.request.POST['state'].upper()
        county_name = self.request.POST['county'].replace("_", " ").title()
        map_data = County.objects.raw(
            'SELECT id, mpoly,'
            ' name, usps_code FROM tigerleaflet_county'
            ' WHERE usps_code=%s AND name=%s',
            [usps_code, county_name],
        )
        geojson = get_geojson(map_data, self.fields)

        return HttpResponse(geojson, content_type='application/json')

tigerleaflet/templates/pages/county.html
{% extends "tigerleaflet-base.html" %}

{% block title %}Showing counties for {{ county }}, {{ state }}{% endblock %}

{% block tigerleaflet_header %}{% endblock %}

{% block tigerleaflet_content %}
  <div id="map" style="width: 600px; height: 400px;" class="leaflet-container-default"></div>
  <script>
    var map = tigerleafletMap('map', [37.22, -90.41], 3);

    var map_data = {
      prefix:   "/tigerleaflet/",
      url:      "{% url 'tigerleaflet:county_data' %}",
      map:      map,
      data:     { 'state':  '{{ state }}',
                  'county': '{{ county }}',
                  },
      function: addCountyData,
    }
    getGeojson(map_data);

  </script>
{% endblock %}

{% block tigerleaflet_javascript %}{% endblock %}

tigerleaflet/templates/pages/index.html
{% extends "tigerleaflet-base.html" %}

{% block title %}tigerleaflet demo map{% endblock %}

{% block tigerleaflet_header %}{% endblock %}

{% block tigerleaflet_content %}
  <script>
    var map = tigerleafletMap('map', [37.22, -90.41], 3);

    var map_data = {
      prefix:   "/tigerleaflet/",
      url:      "{% url 'tigerleaflet:state_data' %}",
      map:      map,
      data:     null,
      function: addStateData,
    }

    getGeojson(map_data);

  </script>
{% endblock %}

{% block tigerleaflet_javascript %}{% endblock %}

tigerleaflet/templates/pages/state.html
{% extends "tigerleaflet-base.html" %}

{% block title %}Showing counties for {{ state }}{% endblock %}

{% block tigerleaflet_header %}{% endblock %}

{% block tigerleaflet_content %}
  <div id="map" style="width: 600px; height: 400px;" class="leaflet-container-default"></div>
  <script>
    var map = tigerleafletMap('map', [37.22, -90.41], 3);

    var map_data = {
      prefix:   "/tigerleaflet/",
      url:      "{% url 'tigerleaflet:county_data' %}",
      map:      map,
      data:     { 'state': '{{ state }}' },
      function: addCountyData,
    }
    getGeojson(map_data);

  </script>
{% endblock %}

{% block tigerleaflet_javascript %}{% endblock %}

tigerleaflet/templates/tigerleaflet-base.html
{% extends "app_base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block title %}{% endblock %}

{% block extra_header %}
  {% leaflet_css %}
  {% leaflet_js %}
  <link rel="stylesheet" href="{% static 'css/tigerleaflet.css' %}">
  <script src='{% static "js/jquery.min.js" %}'></script>
  <script src='{% static "js/tigerleaflet.js" %}'></script>
  {% block tigerleaflet_header %}{% endblock %}
{% endblock %}

{% block content %}
  <div id="map" style="width: 600px; height: 400px;" class="leaflet-container-default"></div>
  {% block tigerleaflet_content %}{% endblock %}
{% endblock %}

{% block extra_javascript %}
  {% block tigerleaflet_javascript %}{% endblock %}
{% endblock %}

tigerleaflet/templates/tigerleaflet_country.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var map = tigerleafletMap('{{ map_name }}', [{{ latitude }}, {{ longitude }}], {{ zoom_level }});

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:country_data' %}",
    map:      map,
    function: goToState,
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
    },
    zoom: false,
  }
  getGeojson(map_data);

</script>

tigerleaflet/templates/tigerleaflet_county.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var map = tigerleafletMap('{{ map_name }}');

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:county_data' %}",
    map:      map,
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
      county              : "{{ county }}",
    },
    zoom:     true,
    function: null,
  }

  getGeojson(map_data);

</script>

tigerleaflet/templates/tigerleaflet_init.html
{% load leaflet_tags %}
{% load geojson_tags %}

{% leaflet_css %}
{% leaflet_js %}

{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'css/tigerleaflet.css' %}">
<script src='{% static "js/jquery.min.js" %}'></script>
<script src='{% static "js/tigerleaflet.js" %}'></script>

tigerleaflet/templates/tigerleaflet_state.html
 <div id={{ map_name }} class="leaflet-container-default"></div>
 <script>
  var map = tigerleafletMap('{{ map_name }}');

  var map_data = {
    prefix:   {{ prefix }},
    url:      "{% url 'tigerleaflet:state_data' %}",
    map:      map,
    data:     {
      csrfmiddlewaretoken : '{{ csrf_token }}',
      state               : "{{ state }}",
    },
    zoom:     true,
    function: goToCounty,
  }

  getGeojson(map_data);

</script>